name: flask-react-starter
dependencies:
  - python=3.11
  - pip
  - pip:
      - alembic==1.13.1
      - blinker==1.8.1
      - click==8.1.7
      - flask==3.0.3
      - flask-cors==4.0.0
      - flask-login==0.6.3
      - flask-migrate==4.0.7
      - flask-sqlalchemy==3.1.1
      - flask-wtf==1.2.1
      - greenlet==3.0.3
      - gunicorn==22.0.0
      - itsdangerous==2.2.0
      - jinja2==3.1.3
      - mako==1.3.3
      - markupsafe==2.1.5
      - packaging==24.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-editor==1.0.4
      - six==1.16.0
      - sqlalchemy==2.0.29
      - typing-extensions==4.11.0
      - werkzeug==3.0.2
      - wtforms==3.1.2
